### ISSUE TITLE
Different results using local and composer loaded Inspekt

### ISSUE THREAD

**Issue by williamsdb** [funkatron/inspekt#8]
When caging my own array and then checking an element of that array I get different result depending on whether I am using the version of Inspekt downloaded from github as opposed to the version from composer.

For example this works without errors:

    <?php
        require_once('inc/Inspekt.php');

        $test = array();
        $test['params'][] = "hello";

        // cage the array
        $params_cage = Inspekt_Cage::Factory($test);
        $one = $params_cage->getAlnum('params/0');
        $two = $params_cage->getInt('params/1');
	
        print_r($params_cage);
     ?>

However, if I run the following:

    <?php
        require __DIR__ . '/vendor/autoload.php';

        // Inspekt initialisation
        use Inspekt\Inspekt;
        use Inspekt\Cage;

        $test = array();
        $test['params'][] = "hello";

        // cage the array
        $params_cage = Cage::Factory($test);
        $one = $params_cage->getAlnum('params/0');
        $two = $params_cage->getInt('params/1');
	
        print_r($params_cage);
    ?>

Gives the following error:

    Fatal error: Uncaught exception 'Inspekt\Exception' with message 'Key '1' does not exist' in /home/ubuntu/workspace/vendor/funkatron/inspekt/src/Inspekt/Cage.php:992 
    Stack trace: #0 /home/ubuntu/workspace/vendor/funkatron/inspekt/src/Inspekt/Cage.php(985): Inspekt\Cage->getValueRecursive(Array, Object(ArrayObject), 1) 
    #1 /home/ubuntu/workspace/vendor/funkatron/inspekt/src/Inspekt/Cage.php(954): Inspekt\Cage->getValueRecursive(Array, Object(ArrayObject)) 
    #2 /home/ubuntu/workspace/vendor/funkatron/inspekt/src/Inspekt/Cage.php(394): Inspekt\Cage->getValue('params/1') 
    #3 /home/ubuntu/workspace/it.php(15): Inspekt\Cage->getInt('params/1') 
    #4 {main} thrown in /home/ubuntu/workspace/vendor/funkatron/inspekt/src/Inspekt/Cage.php on line 992

Given that you cannot check for null on a caged array (I don't think) this latter functionality makes caging of your arrays less useful.

**Comment by funkatron** [comment]
Yeah, that is a change in the newest versions (0.6.x). I made a change yesterday in the `testXXX()` methods, where they will return `false` if the key does not exist. The change is only in the master branch right now. See `6f91ee00d8d49bb7b801bc60f55dd309de72833e` and `f953fb947210e7e3ecd861d5c974cfa02277826a`. With these changes, if you use `$params_cage->getInt()`, I you will get the behavior you expect.
